### ISSUE TITLE
How to calculate the steer vector

### ISSUE THREAD

**Issue by Ryuk17** [jgarciagimenez/GSC_beamforming#1]
Hi, thanks for sharing this code, however I feel confused about the steer vector. The following are my questions:

1.  how to calculate the steer vector in this repo. Is the Leer_Arrays_Signals a ULA/URA/UCA?
2.  in my opinion, there will be a steer vector for each frame but the steer vector is invariant which means that the sound source doesn't move at all, am I correct?

**Comment by YangangCao** [comment]
> Hi, thanks for sharing this code, however I feel confused about the steer vector. The following are my questions:
> 
> 1. how to calculate the steer vector in this repo. Is the Leer_Arrays_Signals a ULA/URA/UCA?
> 2. in my opinion, there will be a steer vector for each frame but the steer vector is invariant which means that the sound source doesn't move at all, am I correct?

1.It is easy to calculate the steer vector, just Baidu, or In Chinese "导向矢量"
2.Steer vector just means  the relative position between array and speaker. Generally, the speaker stands still and steer vector is fixed.
